// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecSysApi.Infrastructure.Context;

namespace RecSysApi.Infrastructure.Migrations
{
    [DbContext(typeof(RecSysApiContext))]
    [Migration("20220612093914_OrdersSupport")]
    partial class OrdersSupport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Account", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.AccountSignupInvitation", b =>
                {
                    b.Property<Guid>("AccountSignupInvitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountSignupInvitationID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountSignupInvitation");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Publisher", b =>
                {
                    b.Property<Guid>("PublisherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PublisherID");

                    b.HasIndex("UserID");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveRefreshTokenToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ActiveRefreshTokenToken");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Licenses.CourseLicense", b =>
                {
                    b.Property<Guid>("CourseLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseLicenseID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseLicenses");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Acknowladged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("AccountID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Bundle", b =>
                {
                    b.Property<Guid>("BundleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BundleID");

                    b.HasIndex("AccountID");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BundleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LargeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SmallDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BundleID");

                    b.HasIndex("OrderID");

                    b.HasIndex("PriceID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Price", b =>
                {
                    b.Property<Guid>("PriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Section", b =>
                {
                    b.Property<Guid>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionID");

                    b.HasIndex("CourseID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Tokens.JwtToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.HasIndex("UserID");

                    b.ToTable("JwtToken");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("VideoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<bool>("HiddenInSearches")
                        .HasColumnType("bit");

                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<Guid>("SectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SourceVideoSourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Transcription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoID");

                    b.HasIndex("SectionID");

                    b.HasIndex("SourceVideoSourceID");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.VideoSlides", b =>
                {
                    b.Property<Guid>("VideoSlidesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mimetype")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Thumb")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Time")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("VideoID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VideoSlidesID");

                    b.HasIndex("VideoID");

                    b.ToTable("VideoSlides");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.VideoSource", b =>
                {
                    b.Property<Guid>("VideoSourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("VideoSourceID");

                    b.ToTable("VideoSource");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Admin", b =>
                {
                    b.HasBaseType("RecSysApi.Domain.Entities.Account.User");

                    b.Property<Guid>("AdminID")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.AccountSignupInvitation", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", null)
                        .WithMany("AccountSignupInvitations")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Publisher", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.User", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecSysApi.Domain.Entities.Tokens.JwtToken", "ActiveRefreshToken")
                        .WithMany()
                        .HasForeignKey("ActiveRefreshTokenToken");

                    b.Navigation("Account");

                    b.Navigation("ActiveRefreshToken");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Licenses.CourseLicense", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", "Account")
                        .WithMany("PurchasedCourses")
                        .HasForeignKey("AccountID");

                    b.HasOne("RecSysApi.Domain.Entities.Products.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID");

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Bundle", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", null)
                        .WithMany("Bundles")
                        .HasForeignKey("AccountID");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Course", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.Account", "Account")
                        .WithMany("Courses")
                        .HasForeignKey("AccountID");

                    b.HasOne("RecSysApi.Domain.Entities.Products.Bundle", null)
                        .WithMany("Courses")
                        .HasForeignKey("BundleID");

                    b.HasOne("RecSysApi.Domain.Entities.Orders.Order", null)
                        .WithMany("Courses")
                        .HasForeignKey("OrderID");

                    b.HasOne("RecSysApi.Domain.Entities.Products.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Section", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Products.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Tokens.JwtToken", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.User", null)
                        .WithMany("UsedRefreshTokensFamily")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Video", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Products.Section", "Section")
                        .WithMany("Videos")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecSysApi.Domain.Entities.VideoSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceVideoSourceID");

                    b.Navigation("Section");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.VideoSlides", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Video", null)
                        .WithMany("Slides")
                        .HasForeignKey("VideoID");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Admin", b =>
                {
                    b.HasOne("RecSysApi.Domain.Entities.Account.User", null)
                        .WithOne()
                        .HasForeignKey("RecSysApi.Domain.Entities.Account.Admin", "UserID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.Account", b =>
                {
                    b.Navigation("AccountSignupInvitations");

                    b.Navigation("Bundles");

                    b.Navigation("Courses");

                    b.Navigation("PurchasedCourses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Account.User", b =>
                {
                    b.Navigation("UsedRefreshTokensFamily");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Bundle", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Products.Section", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("RecSysApi.Domain.Entities.Video", b =>
                {
                    b.Navigation("Slides");
                });
#pragma warning restore 612, 618
        }
    }
}
